from app.schemas.user import UserCreate, UserResponse, UserBase, UserLogin, Token, TokenRefresh
from app.schemas.resume import ResumeCreate, ResumeUpdate, ResumeResponse, ResumeBase
from app.schemas.job import JobCreate, JobUpdate, JobResponse, JobBase
from app.schemas.tailor import (
    TailorRequest,
    TailorResponse,
    QuickMatchRequest,
    QuickMatchResponse,
    TailoredResumeListResponse,
)
from app.schemas.block import (
    BlockBase,
    BlockCreate,
    BlockUpdate,
    BlockResponse,
    BlockListResponse,
    BlockImportRequest,
    BlockImportResponse,
    BlockEmbedRequest,
    BlockEmbedResponse,
    SemanticMatchResult,
    MatchRequest,
    MatchResponse,
    GapAnalysisResponse,
    BlockVerifyRequest,
)
from app.schemas.workshop import (
    DiffSuggestion,
    WorkshopBase,
    WorkshopCreate,
    WorkshopUpdate,
    WorkshopResponse,
    WorkshopListResponse,
    PullBlocksRequest,
    PullBlocksResponse,
    RemoveBlockRequest,
    SuggestRequest,
    SuggestResponse,
    DiffActionRequest,
    DiffActionResponse,
    UpdateSectionsRequest,
    UpdateStatusRequest,
    WritebackRequest,
    WritebackProposal,
    ExportRequest,
)

__all__ = [
    # User schemas
    "UserBase",
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "Token",
    "TokenRefresh",
    # Resume schemas
    "ResumeBase",
    "ResumeCreate",
    "ResumeUpdate",
    "ResumeResponse",
    # Job schemas
    "JobBase",
    "JobCreate",
    "JobUpdate",
    "JobResponse",
    # Tailor schemas
    "TailorRequest",
    "TailorResponse",
    "QuickMatchRequest",
    "QuickMatchResponse",
    "TailoredResumeListResponse",
    # Block schemas
    "BlockBase",
    "BlockCreate",
    "BlockUpdate",
    "BlockResponse",
    "BlockListResponse",
    "BlockImportRequest",
    "BlockImportResponse",
    "BlockEmbedRequest",
    "BlockEmbedResponse",
    "SemanticMatchResult",
    "MatchRequest",
    "MatchResponse",
    "GapAnalysisResponse",
    "BlockVerifyRequest",
    # Workshop schemas
    "DiffSuggestion",
    "WorkshopBase",
    "WorkshopCreate",
    "WorkshopUpdate",
    "WorkshopResponse",
    "WorkshopListResponse",
    "PullBlocksRequest",
    "PullBlocksResponse",
    "RemoveBlockRequest",
    "SuggestRequest",
    "SuggestResponse",
    "DiffActionRequest",
    "DiffActionResponse",
    "UpdateSectionsRequest",
    "UpdateStatusRequest",
    "WritebackRequest",
    "WritebackProposal",
    "ExportRequest",
]
