from app.schemas.user import UserCreate, UserResponse, UserBase, UserLogin, Token, TokenRefresh
from app.schemas.resume import ResumeCreate, ResumeUpdate, ResumeResponse, ResumeBase
from app.schemas.job import JobCreate, JobUpdate, JobResponse, JobBase
from app.schemas.job_listing import (
    JobListingBase,
    JobListingCreate,
    JobListingUpdate,
    JobListingResponse,
    JobListingListResponse,
    JobListingFilters,
    UserJobInteractionResponse,
    SaveJobRequest,
    HideJobRequest,
    ApplyJobRequest,
    JobInteractionActionResponse,
    WebhookJobListing,
    WebhookBatchRequest,
    WebhookBatchResponse,
    ResumeStyle,
    PDFPreviewRequest,
    PDFPreviewResponse,
    SeniorityLevel,
    SortBy,
    SortOrder,
)
from app.schemas.tailor import (
    TailorRequest,
    TailorResponse,
    QuickMatchRequest,
    QuickMatchResponse,
    TailoredResumeListResponse,
)
from app.schemas.block import (
    BlockBase,
    BlockCreate,
    BlockUpdate,
    BlockResponse,
    BlockListResponse,
    BlockImportRequest,
    BlockImportResponse,
    BlockEmbedRequest,
    BlockEmbedResponse,
    SemanticMatchResult,
    MatchRequest,
    MatchResponse,
    GapAnalysisResponse,
    BlockVerifyRequest,
)
from app.schemas.resume_build import (
    DiffSuggestion,
    ResumeBuildBase,
    ResumeBuildCreate,
    ResumeBuildUpdate,
    ResumeBuildResponse,
    ResumeBuildListResponse,
    PullBlocksRequest,
    PullBlocksResponse,
    RemoveBlockRequest,
    SuggestRequest,
    SuggestResponse,
    DiffActionRequest,
    DiffActionResponse,
    UpdateSectionsRequest,
    UpdateStatusRequest,
    WritebackRequest,
    WritebackProposal,
    ExportRequest,
)

# Backward compatibility aliases
WorkshopBase = ResumeBuildBase
WorkshopCreate = ResumeBuildCreate
WorkshopUpdate = ResumeBuildUpdate
WorkshopResponse = ResumeBuildResponse
WorkshopListResponse = ResumeBuildListResponse

__all__ = [
    # User schemas
    "UserBase",
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "Token",
    "TokenRefresh",
    # Resume schemas
    "ResumeBase",
    "ResumeCreate",
    "ResumeUpdate",
    "ResumeResponse",
    # Job schemas
    "JobBase",
    "JobCreate",
    "JobUpdate",
    "JobResponse",
    # Job Listing schemas
    "JobListingBase",
    "JobListingCreate",
    "JobListingUpdate",
    "JobListingResponse",
    "JobListingListResponse",
    "JobListingFilters",
    "UserJobInteractionResponse",
    "SaveJobRequest",
    "HideJobRequest",
    "ApplyJobRequest",
    "JobInteractionActionResponse",
    "WebhookJobListing",
    "WebhookBatchRequest",
    "WebhookBatchResponse",
    "ResumeStyle",
    "PDFPreviewRequest",
    "PDFPreviewResponse",
    "SeniorityLevel",
    "SortBy",
    "SortOrder",
    # Tailor schemas
    "TailorRequest",
    "TailorResponse",
    "QuickMatchRequest",
    "QuickMatchResponse",
    "TailoredResumeListResponse",
    # Block schemas
    "BlockBase",
    "BlockCreate",
    "BlockUpdate",
    "BlockResponse",
    "BlockListResponse",
    "BlockImportRequest",
    "BlockImportResponse",
    "BlockEmbedRequest",
    "BlockEmbedResponse",
    "SemanticMatchResult",
    "MatchRequest",
    "MatchResponse",
    "GapAnalysisResponse",
    "BlockVerifyRequest",
    # Resume Build schemas
    "DiffSuggestion",
    "ResumeBuildBase",
    "ResumeBuildCreate",
    "ResumeBuildUpdate",
    "ResumeBuildResponse",
    "ResumeBuildListResponse",
    "PullBlocksRequest",
    "PullBlocksResponse",
    "RemoveBlockRequest",
    "SuggestRequest",
    "SuggestResponse",
    "DiffActionRequest",
    "DiffActionResponse",
    "UpdateSectionsRequest",
    "UpdateStatusRequest",
    "WritebackRequest",
    "WritebackProposal",
    "ExportRequest",
    # Backward compatibility aliases
    "WorkshopBase",
    "WorkshopCreate",
    "WorkshopUpdate",
    "WorkshopResponse",
    "WorkshopListResponse",
]
