import type { TemplatePreset } from "./types";

export const TEMPLATE_PRESETS: TemplatePreset[] = [
  {
    id: "classic",
    name: "Classic",
    description: "Traditional serif font, generous spacing",
    style: {
      font_family: "Times New Roman",
      font_size_body: 11,
      font_size_heading: 18,
      font_size_subheading: 12,
      line_spacing: 1.4,
      section_spacing: 16,
      entry_spacing: 8,
      margin_top: 0.75,
      margin_bottom: 0.75,
      margin_left: 0.75,
      margin_right: 0.75,
    },
  },
  {
    id: "modern",
    name: "Modern",
    description: "Clean sans-serif, compact layout",
    style: {
      font_family: "Inter",
      font_size_body: 10,
      font_size_heading: 16,
      font_size_subheading: 11,
      line_spacing: 1.3,
      section_spacing: 14,
      entry_spacing: 6,
      margin_top: 0.6,
      margin_bottom: 0.6,
      margin_left: 0.6,
      margin_right: 0.6,
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Maximum content density",
    style: {
      font_family: "Arial",
      font_size_body: 10,
      font_size_heading: 14,
      font_size_subheading: 10,
      line_spacing: 1.2,
      section_spacing: 10,
      entry_spacing: 4,
      margin_top: 0.5,
      margin_bottom: 0.5,
      margin_left: 0.5,
      margin_right: 0.5,
    },
  },
  {
    id: "executive",
    name: "Executive",
    description: "Professional, spacious layout",
    style: {
      font_family: "Georgia",
      font_size_body: 11,
      font_size_heading: 20,
      font_size_subheading: 13,
      line_spacing: 1.5,
      section_spacing: 18,
      entry_spacing: 10,
      margin_top: 1.0,
      margin_bottom: 1.0,
      margin_left: 1.0,
      margin_right: 1.0,
    },
  },
];